select * from T_COMMONCODES
where PARENTCODE = '10001'
		
select MEMBERID, MEMBERNAME, PASSWORD, EMAIL, ENABLED
		from T_MEMBERS
		order by MEMBERNAME
		
		
SELECT * FROM T_ROLES

SELECT * FROM T_AUTHORITIES

DELETE FROM T_COMMONCODES;

1437725864634 Maria Anders Maria@Anders.org

 1438488682757E12 test     test      test   test

 
FILEINFORID=
PHYSICALFILENAME=, 
LOGICALFILENAME=, 
PHYSICALFILEDIRECTORY=, 
FILESIZE=, 
FILETYPE=, 
FILECONTENTTYPE=, 
RELATEDID= 


		select
		BOOKID
		, BOOKNAME
		, PUBLISHER
		, AUTHOR
		, BOOKINFORMATION
			, FILEINFORID
			, PHYSICALFILENAME
			, LOGICALFILENAME
			, PHYSICALFILEDIRECTORY
			, FILESIZE
			, FILETYPE
			, FILECONTENTTYPE
			, PHYSICALTHUMBNAILDIRECTORY
			, PHYSICALTHUMBNAILFILENAME
			, RELATEDID
		from T_BOOKS BOOKS
		left join T_FILEINFORS FILEINFORS
		on BOOKS.BOOKID = FILEINFORS.RELATEDID
		where BOOKID=1438488682757

		insert into T_FILEINFORS (
			FILEINFORID,
			PHYSICALFILENAME,
			LOGICALFILENAME,
			PHYSICALFILEDIRECTORY,
			FILESIZE,
			FILETYPE,
			FILECONTENTTYPE,
			PHYSICALTHUMBNAILDIRECTORY,
			PHYSICALTHUMBNAILFILENAME,
			RELATEDID
		)
		values(
			1438334234937,
			'L_20150731181655183',
			'L.jpg',
			'',
			73794,
			'file',
			'image/jpeg',
			'',
			'',
			'1438334217878'
		)