
/* Drop Tables */

DROP TABLE T_ROLES CASCADE CONSTRAINTS;
DROP TABLE T_AUTHORITIES CASCADE CONSTRAINTS;
DROP TABLE T_LIBRARY_BOOK CASCADE CONSTRAINTS;
DROP TABLE T_BOOKS CASCADE CONSTRAINTS;
DROP TABLE T_COMMONCODES CASCADE CONSTRAINTS;
DROP TABLE T_FILEINFORS CASCADE CONSTRAINTS;
DROP TABLE T_LIBRARYS CASCADE CONSTRAINTS;
DROP TABLE T_MEMBERS CASCADE CONSTRAINTS;
DROP TABLE T_RECODELOGS CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE T_AUTHORITIES
(
	AUTHORITYID varchar2(50 char) NOT NULL,
	AUTHORITYNAME varchar2(50 char) NOT NULL,
	DESCRIPTION varchar2(100 char),
	PRIMARY KEY (AUTHORITYID)
);


CREATE TABLE T_BOOKS
(
	BOOKID number NOT NULL,
	BOOKNAME varchar2(100) NOT NULL,
	PUBLISHER varchar2(50) NOT NULL,
	AUTHOR varchar2(50) NOT NULL,
	BOOKINFORMATION varchar2(2000),
	PRIMARY KEY (BOOKID)
);


CREATE TABLE T_COMMONCODES
(
	COMMONCODEID number NOT NULL,
	-- INSERT MENUALLY
	PARENTCODE varchar2(5) NOT NULL,
	-- INSERT COLUME NAME ON TABLE OR CODE ID
	CHILDCODE varchar2(20) NOT NULL,
	CODENAME varchar2(50),
	DESCRIPTION varchar2(100),
	PRIMARY KEY (COMMONCODEID),
	UNIQUE (PARENTCODE, CHILDCODE)
);


CREATE TABLE T_FILEINFORS
(
	FILEINFORID number NOT NULL,
	-- PHYSICAL_FILE_NAME
	PHYSICALFILENAME varchar2(255) NOT NULL,
	-- LOGICAL_FILE_NAME
	LOGICALFILENAME varchar2(255) NOT NULL,
	-- PHYSICAL_FILE_DIRECTORY
	PHYSICALFILEDIRECTORY varchar2(150),
	-- FILE_SIZE
	FILESIZE number(19,0),
	-- use to need that upload multi file different sort of it.
	FILETYPE varchar2(10),
	FILECONTENTTYPE varchar2(50),
	-- PHYSICAL_THUMBNAIL_DIRECTORY
	PHYSICALTHUMBNAILDIRECTORY varchar2(150),
	-- PHYSICAL_THUMBNAIL_FILE_NAME
	PHYSICALTHUMBNAILFILENAME varchar2(50),
	RELATEDID number NOT NULL,
	PRIMARY KEY (FILEINFORID)
);


CREATE TABLE T_LIBRARYS
(
	LIBRARYID number NOT NULL,
	LIBRARYNAME varchar2(50) NOT NULL,
	LATITUDE varchar2(20),
	LONGITUDE varchar2(20),
	ADDTIONLOCATION varchar2(200),
	ADDTIONAL_INFORMATION varchar2(2000),
	PRIMARY KEY (LIBRARYID)
);


CREATE TABLE T_LIBRARY_BOOK
(
	LIBRARYID number NOT NULL,
	BOOKID number NOT NULL,
	UNIQUE (LIBRARYID, BOOKID)
);


CREATE TABLE T_MEMBERS
(
	-- Physical ID
	MEMBERID number NOT NULL,
	-- Logical ID
	-- 
	EMAIL varchar2(200) NOT NULL UNIQUE,
	MEMBERNAME varchar2(50 char) NOT NULL,
	PASSWORD varchar2(20 char) NOT NULL,
	ENABLED varchar2(1) NOT NULL,
	PRIMARY KEY (MEMBERID)
);


CREATE TABLE T_RECODELOGS
(
	RELTEDID number NOT NULL,
	INSERT_DATE varchar2(20) NOT NULL,
	INSERT_MEMBERID number NOT NULL,
	INSERT_MEMBERNAME varchar2(50) NOT NULL,
	UPDATE_DATE varchar2(20) NOT NULL,
	UPDATE_MEMBERID number NOT NULL,
	UPDATE_MEMBERNAME varchar2(50) NOT NULL,
	PRIMARY KEY (RELTEDID)
);


CREATE TABLE T_ROLES
(
	-- Physical ID
	MEMBERID number NOT NULL,
	AUTHORITYID varchar2(50 char) NOT NULL,
	UNIQUE (MEMBERID, AUTHORITYID)
);



/* Create Foreign Keys */

ALTER TABLE T_ROLES
	ADD FOREIGN KEY (AUTHORITYID)
	REFERENCES T_AUTHORITIES (AUTHORITYID)
;


ALTER TABLE T_LIBRARY_BOOK
	ADD FOREIGN KEY (BOOKID)
	REFERENCES T_BOOKS (BOOKID)
;


ALTER TABLE T_LIBRARY_BOOK
	ADD FOREIGN KEY (LIBRARYID)
	REFERENCES T_LIBRARYS (LIBRARYID)
;


ALTER TABLE T_ROLES
	ADD FOREIGN KEY (MEMBERID)
	REFERENCES T_MEMBERS (MEMBERID)
;



/* Comments */

COMMENT ON COLUMN T_COMMONCODES.PARENTCODE IS 'INSERT MENUALLY';
COMMENT ON COLUMN T_COMMONCODES.CHILDCODE IS 'INSERT COLUME NAME ON TABLE OR CODE ID';
COMMENT ON COLUMN T_FILEINFORS.PHYSICALFILENAME IS 'PHYSICAL_FILE_NAME';
COMMENT ON COLUMN T_FILEINFORS.LOGICALFILENAME IS 'LOGICAL_FILE_NAME';
COMMENT ON COLUMN T_FILEINFORS.PHYSICALFILEDIRECTORY IS 'PHYSICAL_FILE_DIRECTORY';
COMMENT ON COLUMN T_FILEINFORS.FILESIZE IS 'FILE_SIZE';
COMMENT ON COLUMN T_FILEINFORS.FILETYPE IS 'use to need that upload multi file different sort of it.';
COMMENT ON COLUMN T_FILEINFORS.PHYSICALTHUMBNAILDIRECTORY IS 'PHYSICAL_THUMBNAIL_DIRECTORY';
COMMENT ON COLUMN T_FILEINFORS.PHYSICALTHUMBNAILFILENAME IS 'PHYSICAL_THUMBNAIL_FILE_NAME';
COMMENT ON COLUMN T_MEMBERS.MEMBERID IS 'Physical ID';
COMMENT ON COLUMN T_MEMBERS.EMAIL IS 'Logical ID
';
COMMENT ON COLUMN T_ROLES.MEMBERID IS 'Physical ID';



